### PR TITLE
Fixes #28296 - rubocop 0.75 upgrade

### PR DESCRIPTION
**Pull request by lzap**
SSIA

https://github.com/theforeman/foreman/pull/7161

### CODE REVIEW

**Comment by timogoebel** [comment]
Tests are 🔴. I believe we should make the ci job use the rubocop version we specify in the plugin repo.

**Comment by lzap** [comment]
I hate the idea, I maintain this code and I want to be able to decide what's reasonable Rubocop rule and what's not. Not someone who pushes into our template plugin repo.

Test failures seem to be irrelevant?

**Comment by lzap** [comment]
Locally however I do see this:

```
# Running:

........

Rails logs for test_0001_should add a cdrom drive while keeping other parameters when provision_method is bootdisk FAILURE:
F

Failure:
ForemanBootdisk::VmwareTest::#parse_args#test_0001_should add a cdrom drive while keeping other parameters when provision_method is bootdisk [/home/lzap/work/foreman_bootdisk/test/unit/concerns/compute_resources/vmware_test.rb:69]:
--- expected
+++ actual
@@ -1 +1 @@
-{:cpus=>"1", :provision_method=>"bootdisk", :cdroms=>[#<Mock:cdrom>], :boot_order=>["cdrom", "disk"], :boot_retry=>10}
+{:cpus=>"1", :provision_method=>"bootdisk"}



bin/rails test _bootdisk/test/unit/concerns/compute_resources/vmware_test.rb:55

..............................

Rails logs for test_0001_should include bootdisk FAILURE:
F

Failure:
ForemanBootdisk::VmwareTest::#capabilities#test_0001_should include bootdisk [/home/lzap/work/foreman_bootdisk/test/unit/concerns/compute_resources/vmware_test.rb:79]:
Expected [:build, :image] to include :bootdisk.


bin/rails test _bootdisk/test/unit/concerns/compute_resources/vmware_test.rb:78

...

Rails logs for test_0001_calls client with cdrom drive and correct boot order when bootdisk provisioning FAILURE:
F

Failure:
ForemanBootdisk::VmwareTest::#new_vm#test_0001_calls client with cdrom drive and correct boot order when bootdisk provisioning [/home/lzap/work/foreman_bootdisk/test/unit/concerns/compute_resources/vmware_test.rb:37]:
Expected: ["network", "disk"]
  Actual: ["cdrom", "disk"]


bin/rails test _bootdisk/test/unit/concerns/compute_resources/vmware_test.rb:30

.........

Finished in 8.550893s, 6.1982 runs/s, 13.6828 assertions/s.
53 runs, 117 assertions, 3 failures, 0 errors, 0 skips
```

**Comment by lzap** [comment]
Looks like this should do it: https://github.com/theforeman/foreman/pull/7227

**Comment by lzap** [comment]
Well it's green now.

**Comment by timogoebel** [comment]
Thanks, @lzap.

**Pull request merged**
