### PR TITLE
Fixes #23738 - added generic static host template

### PR DESCRIPTION
**Pull request by lzap**
New template which can be used in Administer - Settings - Boot disk for Generic
host image generation.

Replaces:

* https://github.com/theforeman/foreman_bootdisk/pull/15
* https://github.com/theforeman/foreman_bootdisk/pull/61

/CC @glimpsovstar

### CODE REVIEW

**Comment by lzap** [comment]
Resolved conflicts, this one does not break anything (as long as the seed works fine) @timogoebel ?

**Comment by lzap** [comment]
I fixed reasonable things and then removed those pesky checks.

**Comment by timogoebel** [comment]
Tests are still red.

**Comment by lzap** [comment]
Please tell me, how to run this Rubocop locally so I can see the same errors? I don't have these locally. I did not see them even the last time...

**Comment by lzap** [comment]
```
[lzap@box foreman_bootdisk]$ be rubocop
Foreman source code is not present. To get the latest version, run:

  rake setup:foreman_prepare

and try again.
Inspecting 43 files
...........................................

43 files inspected, no offenses detected
```

**Comment by timogoebel** [comment]
> Please tell me, how to run this Rubocop locally so I can see the same errors?

I guess you need to run in from the core dir (`bundle exec rubocop -a ../foreman_discovery/`), Jenkins ignores the version set in the plugin bundle. It always uses the version specified in core.

**Comment by lzap** [comment]
Since you approved, I am going to merge this it's all green if you don't mind. This fixes broken tests, I want to rebase another PR on top of this.

**Pull request merged**
