### PR TITLE
Bkearney/downstream strings

### PR DESCRIPTION
**Pull request by bkearney**
This commit contains new and modified translations. A summary of the 
changes can be found at 

https://gist.github.com/bkearney/c71502281655e2032a02

### CODE REVIEW

**Comment by bkearney** [comment]
@Claer, I have pushed in a new commit with just your changes. I am happy to squash when we are ready to merge.

**Comment by lzap** [comment]
Please rebase, I will merge.

**Comment by lzap** [comment]
Oh before that please paste `msgfmt -c locale/*/*.po` output. Discovery had fatal parsing errors :(

**Comment by lzap** [comment]
Use this command, the above one does not work:

```
find locale/*/*po | xargs -n1 msgfmt -c
```

**Comment by bkearney** [comment]
@lzap:
[bkearney@fivehole foreman_bootdisk] $ find locale/*/*po | xargs -n1 msgfmt -c
locale/en/foreman_bootdisk.edit.po:6: invalid nplurals value
locale/en/foreman_bootdisk.edit.po:6: warning: header field 'Language' still has the initial default value
msgfmt: found 2 fatal errors
msgfmt: locale/en/foreman_bootdisk.po: warning: PO file header fuzzy
                                       warning: older versions of msgfmt will give an error on this
locale/en/foreman_bootdisk.po:7: invalid nplurals value
locale/en/foreman_bootdisk.po:7: warning: header field 'Language' still has the initial default value
msgfmt: found 2 fatal errors

**Comment by domcleal** [comment]
Seems to still be missing reviews for string changes for non-FR languages.

**Comment by lzap** [comment]
I am afraid we won't be able to verify all of these in decent timeframe, but anyway. Reviewed by translators:

* [x] fr
* [ ] it
* [ ] ja
* [ ] ko
* [ ] ru
* [ ] de
* [ ] es
* [ ] pt_BR
* [ ] zh_CN
* [ ] zh_TW

**Comment by domcleal** [comment]
Then please remove the changes from unreviewed languages and only add new strings.

**Comment by bkearney** [comment]
@domcleal there is no one who will review it. Since these were reviewed downstream, by professional translators, should that not count?

**Comment by domcleal** [comment]
No, I won't blindly overwrite existing work without it being checked.  New strings are fine, but I've no desire to take unreviewed changes.

**Comment by bkearney** [comment]
If I look at transifex, I see that large quantity of strings are not reviewed (https://www.transifex.com/foreman/foreman/viewstrings/#fr/foreman/12973094). Can you help me understand how strings are reviewed / approved using the current process? That will help me to understand how pushing these strings is better/worse then the current process.

**Pull request closed without merging**
