### PR TITLE
fixes #19013 - vmware: retry iso boot

### PR DESCRIPTION
**Pull request by timogoebel**
Replacement for https://github.com/theforeman/foreman/pull/4408.

### CODE REVIEW

**Comment by lzap** [comment]
This is ACK, it only adds a value to hash.

**Comment by timogoebel** [comment]
@domcleal : Are you planning on reviewing this? Do you need any help?

**Comment by timogoebel** [comment]
@lzap: Since you already acked this and you have permission now: Is this ready?

**Comment by domcleal** [comment]
Thanks @timogoebel.

**Pull request merged**
