### PR TITLE
Fixes #19733 - fixed duplicate templates

### PR DESCRIPTION
**Pull request by lzap**
Please let me know if you plan new plugin release and I will do downstream steps accordingly. I'd appreciate if this could be beginning next week. Thanks.

### CODE REVIEW

**Comment by lzap** [comment]
Failure not related, for the context go to ticket.

**Comment by ares** [comment]
What is the status here? This is really painful.

**Comment by bkearney** [comment]
@lzap bump

**Comment by lzap** [comment]
@bkearney wrong ping, I am not maintainer of this git repo. I guess that would be @domcleal

**Comment by bkearney** [comment]
@domcleal can you take a look, or can we bless @lzap to merge/release this gem?

**Comment by timogoebel** [comment]
@domcleal: Could you please review this PR and release a new version with this fix contained? This bug is really annoying. If you want to be the sole maintainer of this repo, please do your job. This behavior is very unprofessional.

**Comment by timogoebel** [comment]
[test]

**Comment by timogoebel** [comment]
Merged, thanks @lzap.

I was able to reproduce the bug. This fixes this for me. We still need to figure out how why the uniqueness validation on the name of the Provisioning Template in core did not prevent this from happening in the first place.

https://github.com/theforeman/foreman/blob/6864f7def02e65b8d4bbfda2ddd73e19cff000c7/app/models/provisioning_template.rb#L19

**Pull request merged**
