### PR TITLE
fixes #24147 - use new template renderer

### PR DESCRIPTION
**Pull request by timogoebel**
This needs https://github.com/theforeman/foreman/pull/5683.

### CODE REVIEW

**Comment by timogoebel** [comment]
[test foreman_bootdisk]

**Comment by timogoebel** [comment]
[test foreman_bootdisk]

**Comment by lzap** [comment]
Looks like Rails 5 issue in migrations.

```
NoMethodError: undefined method `get_all_versions' for ActiveRecord::Migrator:Class
/var/lib/workspace/workspace/foreman_bootdisk-pull-request/database/postgresql/label/fast/ruby/2.3/plugin/db/migrate/20140522185700_change_templatekind_to_bootdisk.rb:3:in `<class:FakeConfigTemplate>'
/var/lib/workspace/workspace/foreman_bootdisk-pull-request/database/postgresql/label/fast/ruby/2.3/plugin/db/migrate/20140522185700_change_templatekind_to_bootdisk.rb:2:in `<class:ChangeTemplatekindToBootdisk>'
```

Do you want to tackle this as well?

**Comment by timogoebel** [comment]
Rebased. Fingers crossed. :-)

**Comment by lzap** [comment]
Sorry this one's my bad! :-)

SyntaxError: /var/lib/workspace/workspace/foreman_bootdisk-pull-request/database/postgresql/label/fast/ruby/2.3/foreman/app/models/concerns/fog_extensions/openstack/server.rb:76: syntax error, unexpected end-of-input, expecting keyword_end

[test foreman_bootdisk]

**Comment by timogoebel** [comment]
@lzap: I have updated this PR. It now used a dedicated scope to render the bootdisk templates. The commit also removes unnecessary regex to change the rendered template and adds a lot of tests.
Please review and test.

**Comment by timogoebel** [comment]
Test failures look unrelated to me.

**Comment by lzap** [comment]
Works great, thanks!

**Pull request merged**
