### PR TITLE
#27651 Provision using vlan tagging boot iso

### PR DESCRIPTION
**Pull request by vgunasek**
Using this updated template we will be able to provision the host on the VLAN tagged network.

We have to compile the new IPXE template with vcreate command --> https://ipxe.org/cmd/vcreate

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Comment by timogoebel** [comment]
> We have to compile the new IPXE template with vcreate command --> https://ipxe.org/cmd/vcreate

Thanks a bunch for the patch!

Right now we rely on iPXE shipped with the OS. I'm reluctant on accepting this because it requires users to compile iPXE themselves. Is there a way to detect if iPXE supports the feature / was built with this?
@lzap: What do you think?

**Comment by lzap** [comment]
I don't believe that a missing compilation option should block us from not accepting reasonable features. The patch is not correct tho, there is an unclosed if block. Here is how I would suggest it:

```diff
diff --git a/app/views/foreman_bootdisk/host.erb b/app/views/foreman_bootdisk/host.erb
index 6b3e9c6..e0298f6 100644
--- a/app/views/foreman_bootdisk/host.erb
+++ b/app/views/foreman_bootdisk/host.erb
@@ -40,7 +40,16 @@ goto loop_success
 
 :loop_success
 echo Configuring net${idx} for static IP address <%= ip %>
-ifopen net${idx}
+<% if interface.tag.present? && interface.attached_to.present? %>
+  echo Configuring tagging for VLAN <%= interface.tag %>
+  echo WARNING: The following command (vcreate) will fail unless iPXE was
+  echo compiled with VLAN_CMD flag. See: https://ipxe.org/cmd/vcreate
+  vcreate --tag <%= interface.tag %> net${idx}
+  ifopen net${idx}-<%= interface.tag %>
+<% else %>
+  ifopen net${idx}
+<% end %>
+
 # netX = last opened NIC
 set netX/ip <%= ip %>
 set netX/netmask <%= mask %>
```

**Comment by lzap** [comment]
Do you want to continue with the patch?

**Comment by lzap** [comment]
Hopefully someone can pick this up, finish it, test it. Closing for now, feel free to reopen. Thank you for the contribution!

**Pull request closed without merging**
