### PR TITLE
Added hardware compatibility list

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by domcleal** [comment]
This belongs in iPXE, not in bootdisk as it's specific to iPXE versions.

**Comment by lzap** [comment]
What you mean? I have a user asking - my system does not boot via bootdisk. Is it compatible? But I just learned on the IRC that Full Host is isolinux based, I can add a note how to workaround incompatible hardware.

**Comment by domcleal** [comment]
Whether it's compatible depends on the version of iPXE used.  Wouldn't it be better to keep that information in the iPXE project and reference it?

**Comment by lzap** [comment]
Hmm it's actually here: http://ipxe.org/appnote/hardware_drivers

**Pull request closed without merging**
