### PR TITLE
Fixes #31063 - generate full host bootdisk when possible

### PR DESCRIPTION
**Pull request by lzap**
In order for VMWare to work in EFI mode, bootdisk should generate full host bootdisk.

### CODE REVIEW

**Review by timogoebel — APPROVED** [review]
Looks good.

**Comment by lzap** [comment]
For the record, https://community.theforeman.org/t/vmware-boot-disk/20814

Let's wait if this works.

**Comment by lzap** [comment]
The last versions finally works, there was an overlook in argument passing: https://community.theforeman.org/t/vmware-boot-disk/20814

**Comment by timogoebel** [comment]
Thanks!

**Pull request merged**
