### PR TITLE
Fixes #17893 - Do not preview bootdisk templates

### PR DESCRIPTION
**Pull request by xprazak2**
needs [this](https://github.com/theforeman/foreman/pull/4211) to work

### CODE REVIEW

**Comment by domcleal** [comment]
Why should the preview be disabled?

**Comment by xprazak2** [comment]
The preview ends up in error, I based this on @lzap's [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1393848#c4) saying that preview is not relevant here.

**Comment by domcleal** [comment]
The error should be fixed then, this PR makes little sense to me.

**Comment by lzap** [comment]
I think we should prevent association than preview, if we want to fix it like that. I think this could be simply better documentation or similar.

**Pull request closed without merging**
